### ISSUE TITLE
'ConnectionRefusedError: [Errno 111]' when running 'phort.py status' after start

### ISSUE THREAD

**Issue by naltun** [naltun/phort#2]
In fact, I can't connect to the Internet at all after starting the program. I am not sure if the issue lies with Python or with iptables.

The following traceback is given when running `phort.py status` (after `phort.py start`):

```python
➜  phort git:(master) ✗ python phort.py status
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fdcc6b26358>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='check.torproject.org', port=443): Max retries exceeded with url: /api/ip (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdcc6b26358>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "phort.py", line 9, in <module>
    cli()
  File "/home/naltun/workspace/phort/phort/functions.py", line 81, in cli
    checkConn()
  File "/home/naltun/workspace/phort/phort/functions.py", line 46, in checkConn
    req = requests.get(api)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='check.torproject.org', port=443): Max retries exceeded with url: /api/ip (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdcc6b26358>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by naltun** [comment]
Reddit thread on `r/linuxquestions` has been started [here](https://www.reddit.com/r/linuxquestions/comments/b0bxj2/python_script_running_iptables_internet_becomes/).
